name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: "10"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "pnpm"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "pnpm install"
        env:
          MNEMONIC:
            "test test test test test test test test test test test junk"
          SEPOLIA_RPC_URL: "http://localhost:8545"
          DEPLOYER_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

      - name: "Lint"
        run: |
          pnpm lint

      - name: "Build"
        run: |
          pnpm build

      - name: "Test"
        run: |
          pnpm test

        env:
          MNEMONIC:
            "test test test test test test test test test test test junk"
          SEPOLIA_RPC_URL: "http://localhost:8545"
          DEPLOYER_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
