name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: "10"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "pnpm"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "pnpm install"
        env:
          MNEMONIC:
            "exchange vintage ocean narrow danger return culture ignore trim solve clock hidden buddy wise emotion"
          SEPOLIA_RPC_URL: "https://sepolia.infura.io/v3/YOUR-PROJECT-ID"

      - name: "Lint the code"
        run: "cd packages/hardhat && pnpm lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Test the contracts"
        run: "cd packages/hardhat && pnpm test:all"
        env:
          MNEMONIC:
            "exchange vintage ocean narrow danger return culture ignore trim solve clock hidden buddy wise emotion"
          SEPOLIA_RPC_URL: "https://sepolia.infura.io/v3/YOUR-PROJECT-ID"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
